[package]
name = "brickgen"
version = "0.1.0"
edition = "2024"

[dependencies]
brickadia = "0.1"
strum = "0.27"
strum_macros = "0.27"
num-traits = "0.2"
rayon = "1.8"
image = { version = "0.25", features = ["rayon"] }
imageproc = "0.25"

